### ISSUE TITLE
how to make wait until the process is finished?

### ISSUE THREAD

**Issue by Dagimal** [AndoreKun/loading-bars#1]
I really like your project, I want to ask, how to make it wait until the function execution process is finished? sorry my english is bad

**Comment by AndoreKun** [comment]
Hello! Thank you, I'm very happy to know that you like my project! Do you wish for the script only to continue if the loading process has finished, right?

**Comment by Dagimal** [comment]
yes please :D

**Comment by AndoreKun** [comment]
Here it goes, it's basically this 

https://user-images.githubusercontent.com/74919142/124496525-706be080-ddb1-11eb-8854-bf2e2929ca90.mp4
